### ISSUE TITLE
Do not work "on" & "except" scenarios inside of "if" and "then"

### ISSUE THREAD

**Issue by Briareos17** [slinstj/Yii-Conditional-Validator#6]
array('check', 'ext.YiiConditionalValidator',
                'if' => array(
                    array('check', 'compare', 'compareValue' => 0),
                ),
                'then' => array(
                    array('toDo', 'required', 'except' => 'scenario'),
                ),
            ),

$item = Model::model()->findByPk(intval($data['id']));
$item->scenario = 'scenario';
$item->attributes = $data;

When called $item->save(), model returns error toDo can not be blank;

**Comment by sdlins** [comment]
What happens when you put 'except' in the own conditional validator?

``` [php]
array('check', 'ext.YiiConditionalValidator',
    'if' => array(
        array('check', 'compare', 'compareValue' => 0),
    ),
    'then' => array(
        array('toDo', 'required'),
    ),
    'except' => 'scenario', // here
),
```

**Comment by Briareos17** [comment]
I will try, thanks!

2015-03-27 17:32 GMT+02:00 Sidney Lins notifications@github.com:
